### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-toggl-source#1]
### Description
Toggl is a timetracking app. There is a reporting api but that provides summary level statistics we do not care about right now. For the initial build, we will focus on the core api, specifically the `user`, `workspace` and `time entries` endpoints.

Toggl is organized around workspaces and a workspace id is required for nearly every request.

**Workspaces** -
https://www.toggl.com/api/v8/workspaces
https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-projects
https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-clients
 https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-users
https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-groups
https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-tags
https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-tasks

**Time Entries**
https://www.toggl.com/api/v8/time_entries

### Requirements
- [ ] Empty results will return `null`. If this occurs, ignore the response
- [ ] Stay under rate limit of 1 request/second
- [ ] Provide `getAll` option for workspace id to pull all ids for the user and pass the array to the appropriate endpoint
  - [ ] First hit the workspaces endpoint to get all workspaces the user has access to
  - [ ] Pull the workspace_ids into a separate array
  - [ ] Iterate through this array, passing each id to the appropriate endpoint
  - [ ] Append each response to a single output object in same format as when requesting a single workspaceId
- [ ] Time Entries should fill `startDate` dynamically as the executionDate from Aries with endDate as a time in the future.

### Relevant Links
https://github.com/7eggs/node-toggl-api

### Possible Config
```
{
"workspaceId": "1834588",
"method":"getProjectData",
"projectId":"getAll"
}
```

**Comment by ryw** [comment]
no more work on aries
